


```{r}

library(tidyverse)
library(purrr)
```


```{r}
try_3 = function(n = 30, mu, sigma = 5) 
  {
  sim_da = tibble(
    x = rnorm(n, mean = mu, sd = sigma)
  )
 sim_da %>% 
    summarize(
      t.test(x, mu = 0, conf.level = 0.95) %>% 
      broom::tidy() )
      }

```


Run the function 5000 times, obtain the dataset of interest when mu=0, select the mu_hat and p.value. 

Create the dataset of interest which contains the values we want when mu ranges from 0 to 6

```{r}
sim_mu_final_try = 
  tibble( mu = 0:6) %>% 
  mutate(
    output_mu_others = map(.x = mu, ~rerun (50, try_3(mu = .x))),
    other_mu_dfs = map(output_mu_others, bind_rows)
  ) %>% 
  select(-output_mu_others) %>% 
  unnest(other_mu_dfs)

```


plot bar version
```{r}
plot_one  =
sim_mu_final  %>% 
  group_by(mu) %>%
  mutate(outcome = ifelse(p.value < 0.05, "reject", "not reject") )%>% 
   summarize(num_reject = sum ( outcome == "reject"),
             num_total= n()) %>% 
  mutate(rejection_proportion = num_reject / num_total ) %>% 
ggplot(aes(x = mu, y = rejection_proportion, fill = mu)) + geom_col() + theme(legend.position = "none") +labs(title = "Power of the test",x = "True value of mean",y = "Proportion of times the null was rejected"
  )+theme(legend.position = "none") 

plot_one 

```




```{r}
sim_mu_final %>% 
  mutate( mu = as.factor(mu))
```